{{- if .Values.euler_copilot.vectorize.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: vectorize-secret-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  .env: |-
{{ tpl (.Files.Get "configs/vectorize/.env") . | indent 4 }}
{{- end }}