{{- if .Values.euler_copilot.vectorize.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: vectorize-agent-service-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.euler_copilot.vectorize.service.type }}
  selector:
    app: vectorize-{{ .Release.Name }}
  ports:
    - port: 8001
      targetPort: 8001
      {{- if (and (eq .Values.euler_copilot.vectorize.service.type "NodePort") .Values.euler_copilot.vectorize.service.nodePort) }}
      nodePort: {{ .Values.euler_copilot.vectorize.service.nodePort }}
      {{- end }}
{{- end }}
