apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-config-custom
  namespace: euler-copilot
data:
  configuration.yaml: |
    ---
    theme: 'light'
    server:
      address: 'tcp://0.0.0.0:9091/'
    log:
      level: 'info'
      format: 'text'
    
    # 身份验证后端
    authentication_backend:
      password_reset:
        disable: true
      refresh_interval: '5 minutes'
      file:
        path: '/config/users.yml'
        password:
          algorithm: 'argon2id'
          iterations: 1
          salt_length: 16
          parallelism: 8
          memory: 1024
    
    # 访问控制
    access_control:
      default_policy: 'one_factor'
    
    # 会话配置
    session:
      name: 'authelia_session'
      same_site: 'lax'
      inactivity: '5 minutes'
      expiration: '1 hour'
      remember_me: '1 month'
      cookies:
        - domain: '127.0.0.1'
          authelia_url: 'http://127.0.0.1:30091'
    
    # 存储配置
    storage:
      encryption_key: 'insecure_storage_encryption_key_change_me_in_production'
      local:
        path: '/config/db.sqlite3'
    
    # 通知配置
    notifier:
      disable_startup_check: true
      filesystem:
        filename: '/config/notification.txt'
    
    # 禁用不需要的功能
    totp:
      disable: true
    webauthn:
      disable: true
    duo_api:
      disable: true
    
    # 限流配置
    regulation:
      max_retries: 3
      find_time: '2 minutes'
      ban_time: '5 minutes'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-users-custom
  namespace: euler-copilot
data:
  users.yml: |
    users:
      openEuler:
        displayname: "openEuler"
        password: "$argon2id$v=19$m=65536,t=3,p=4$eHA4/xN5ZQB0Pl+Larrf8A$M7+SLwWQymLJQjUfEf/zin+xAEQ1EW8IcHet6tFcBvo"  # password: openEuler12#$
        email: openEuler@example.com
        groups:
          - admins
          - dev
