# Authelia官方Chart配置文件

# 基础镜像配置
image:
  tag: "4.39.13"

# 服务配置
service:
  type: NodePort
  nodePort: 30091

# 持久化存储
persistence:
  enabled: true
  size: 1Gi

# Pod配置
pod:
  kind: 'Deployment'
  replicas: 1

# 使用现有的Secret
secret:
  existingSecret: "authelia-users"