{{- if .Values.euler_copilot.rag.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: rag-secret-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  .env: |-
{{ tpl (.Files.Get "configs/rag/.env") . | indent 4 }}
    
  prompt_template.yaml: |-
{{ .Files.Get "configs/rag/prompt_template.yaml" | indent 4 }}
{{- end }}