FROM hub.oepkgs.net/openeuler/openeuler:22.03-lts-sp4

ENV PATH /home/eulercopilot/.local/bin:$PATH
RUN sed -i 's|repo.openeuler.org|mirrors.nju.edu.cn/openeuler|g' /etc/yum.repos.d/openEuler.repo && \
    sed -i '/metalink/d' /etc/yum.repos.d/openEuler.repo && \
    sed -i '/metadata_expire/d' /etc/yum.repos.d/openEuler.repo && \
    yum update -y &&\
    yum install -y python3 python3-pip shadow-utils findutils &&\
    groupadd -g 1001 eulercopilot && useradd -u 1001 -g eulercopilot eulercopilot &&\
    yum clean all

USER eulercopilot

COPY --chown=1001:1001 requirements.txt .

RUN pip3 install --no-cache-dir -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple && \
    chmod -R 750 /home/eulercopilot