{{- if .Values.agents.ai_infra.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: ai-infra-service-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.agents.ai_infra.service.type }}
  selector:
    app: ai-infra-{{ .Release.Name }}
  ports:
    - port: 8101
      targetPort: 8101
      {{- if (and (eq .Values.agents.ai_infra.service.type "") .Values.agents.ai_infra.service.nodePort) }}
      nodePort: {{ .Values.agents.ai_infra.service.nodePort }}
      {{- end }}
{{- end }}
