{{- if .Values.authhub.web.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authhub-web-ingress-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  - host: {{ .Values.globals.domain }}
    http:
      paths:
      - path: {{ .Values.authhub.web.ingress.prefix }}
        pathType: Prefix
        backend:
          service:
            name: authhub-web-service-{{ .Release.Name }}
            port:
              number: 8000
{{- end }}