{{- if .Values.authhub.web.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: authhub-web-secret-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  authhub.nginx.conf: |-
{{ tpl (.Files.Get "configs/web/authhub.nginx.conf") . | indent 4 }}
{{- end }}