{{- if .Values.authhub.web.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authhub-web-deploy-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: authhub-web-{{ .Release.Name }}
spec:
  replicas: {{ .Values.globals.replicaCount }}
  selector:
    matchLabels:
      app: authhub-web-{{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/web/authhub-web-secret.yaml") . | sha256sum }}
      labels:
        app: authhub-web-{{ .Release.Name }}
    spec:
      automountServiceAccountToken: false
      containers:
        - name: authhub-web
          image: "{{if ne ( .Values.authhub.web.image.registry | toString ) ""}}{{ .Values.authhub.web.image.registry }}{{ else }}{{ .Values.globals.imageRegistry }}{{ end }}/{{ .Values.authhub.web.image.name }}:{{ .Values.authhub.web.image.tag | toString }}"
          imagePullPolicy: {{ if ne ( .Values.authhub.web.image.imagePullPolicy | toString ) "" }}{{ .Values.authhub.web.image.imagePullPolicy }}{{ else }}{{ .Values.globals.imagePullPolicy }}{{ end }}
          ports:
            - containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 8000
              scheme: HTTP
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 90
          volumeMounts:
            - name: authhub-web-secret-volume
              mountPath: /etc/nginx/conf.d
          securityContext:
            readOnlyRootFilesystem: {{ .Values.authhub.web.readOnly }}
          resources:
            {{- toYaml .Values.authhub.web.resources | nindent 12 }}
      volumes:
        - name: authhub-web-secret-volume
          secret:
            secretName: authhub-web-secret-{{ .Release.Name }}
            items:
              - key: authhub.nginx.conf
                path: authhub.nginx.conf
{{- end }}
