{{- if .Values.authhub.web.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: authhub-web-service-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.authhub.web.service.type }}
  selector:
    app: authhub-web-{{ .Release.Name }}
  ports:
    - port: 8000
      targetPort: 8000
      {{- if (and (eq .Values.authhub.web.service.type "NodePort") .Values.authhub.web.service.nodePort) }}
      nodePort: {{ .Values.authhub.web.service.nodePort }}
      {{- end }}
{{- end }}