{{- $databaseSecret := (lookup "v1" "Secret" .Release.Namespace "euler-copilot-database") }}
{{- if not $databaseSecret}}
apiVersion: v1
kind: Secret
metadata:
  name: euler-copilot-database
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  redis-password: {{ randAlphaNum 20 }}
  mongo-password: {{ randAlphaNum 20 }}
  minio-password: {{ randAlphaNum 20 }}
  pgsql-password: {{ randAlphaNum 20 }}
{{- end }}