# 全局设置
globals:
  # [必填] 部署副本数
  replicaCount: 1
  # [必填] 镜像仓库
  imageRegistry: "hub.oepkgs.net/neocopilot"
  # [必填] 镜像拉取策略
  imagePullPolicy: IfNotPresent
  # [必填] 域名
  domain: "eulercopilot.test.com"
  # [必填] Postgresql设置
  pgsql:
    # [必填] 主机
    host: "pgsql-service.euler-copilot.svc.cluster.local"
    # [必填] 端口
    port: 5432
    # [必填] 用户
    user: "postgres"
    # [必填] 密码
    password: ""
  # [必填] LLM设置
  llm:
    # [必填] 模型名称
    model: ""
    url: ""
    key: ""
    max_tokens: 8192

witchaind:
  minio:
    # [必填] 是否部署MinIO实例
    enabled: true
    # 镜像设置
    image:
      # 镜像仓库。留空则使用全局设置。
      registry: ""
      # [必填] 镜像名
      name: "minio"
      # [必填] 镜像标签
      tag: "empty"
      # 拉取策略。留空则使用全局设置。
      imagePullPolicy: ""
    # 性能限制设置
    resources: {}
    # [必填] 容器根目录只读
    readOnly: false
    # [必填] PersistentVolume大小设置
    persistentVolumeSize: 20Gi
    # [必填] 密码设置
    password: ""
    # Service设置
    service:
      # [必填] Service类型，ClusterIP或NodePort
      type: ClusterIP
      # 当类型为nodePort时，填写主机的端口号
      nodePort:
  redis:
    # [必填] 是否部署Redis实例
    enabled: true
    # 镜像设置
    image:
      # 镜像仓库。留空则使用全局设置。
      registry: ""
      # [必填] 镜像名
      name: redis
      # [必填] 镜像标签，为7.4-alpine或7.4-alpine-arm
      tag: 7.4-alpine
      # 拉取策略。留空则使用全局设置
      imagePullPolicy: ""
    # 性能限制设置
    resources: {}
    # [必填] 容器根目录只读
    readOnly: false
    # 密码设置
    password: ""
    # Service设置
    service:
      # [必填] Service类型，ClusterIP或NodePort
      type: ClusterIP
      # 当类型为nodePort时，填写主机的端口号
      nodePort:

  web:
    # [必填] 是否部署witChainD Web前端服务
    enabled: true
    # 镜像设置
    image:
      # 镜像仓库。留空则使用全局设置。
      registry: ""
      # [必填] 镜像名
      name: "data_chain_web" 
      # [必填] 镜像标签
      tag: "1230"
      # 拉取策略。留空则使用全局设置。
      imagePullPolicy: ""
    # 性能限制设置
    resources: {}
    # [必填] 容器根目录只读
    readOnly: false
    # Service设置
    service:
      # [必填] Service类型，ClusterIP或NodePort
      type: ClusterIP
      # 当类型为nodePort时，填写主机的端口号
      nodePort: 
    # Ingress设置
    ingress:
      # [必填] 是否启用Ingress
      enabled: true
      # [必填] URL前缀
      prefix: "/"

  backend:
    # [必填] 是否部署PostgreSQL实例
    enabled: true
    # 镜像设置
    image:
      # 镜像仓库。留空则使用全局设置。
      registry: ""
      # [必填] 镜像名
      name: data_chain_back_end
      # [必填] 镜像标签，为pg16或pg16-arm
      tag: "0.9.2"
      # 拉取策略。留空则使用全局设置。
      imagePullPolicy: ""
    # 性能限制设置
    resources: {}
    # [必填] 容器根目录只读
    readOnly: false
    # Service设置
    service:
      # [必填] Service类型，ClusterIP或NodePort
      type: ClusterIP
      # 当类型为nodePort时，填写主机的端口号
      nodePort: 
    # [必填] Embedding模型URL
    embedding: ""
    # [必填] 密钥设置
    security:
      # [必填] CSRF密钥
      csrf_key: ""
      # [必填] 工作密钥1
      half_key_1: ""
      # [必填] 工作密钥2
      half_key_2: ""
      # [必填] 工作密钥3
      half_key_3: ""
