{{- if .Values.agents.tune.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: tune-secret-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  .env.yaml: |-
{{ tpl (.Files.Get "configs/tune/.env.yaml") . | indent 4 }}
  app_config.yaml: |-
{{ tpl (.Files.Get "configs/tune/app_config.yaml") . | indent 4 }}
  knob_rag_config.json: |-
{{ tpl (.Files.Get "configs/tune/knob_rag_config.json") . | indent 4 }}
  optimize_config.yaml: |-
{{ tpl (.Files.Get "configs/tune/optimize_config.yaml") . | indent 4 }}
{{- end }}