{{- if .Values.witchaind.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: witchaind-backend-service-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.witchaind.backend.service.type }}
  selector:
    app: witchaind-backend-{{ .Release.Name }}
  ports:
    - port: 9988
      targetPort: 9988
      {{- if (and (eq .Values.witchaind.backend.service.type "NodePort") .Values.witchaind.backend.service.nodePort) }}
      nodePort: {{ .Values.witchaind.backend.service.nodePort }}
      {{- end }}
{{- end }}