{{- if .Values.witchaind.web.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: witchaind-web-ingress-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  - host: {{ .Values.globals.domain }}
    http:
      paths:
      - path: {{ .Values.witchaind.web.ingress.prefix }}
        pathType: Prefix
        backend:
          service:
            name: witchaind-web-service-{{ .Release.Name }}
            port:
              number: 9888
{{- end }}
