openapi: 3.1.0
info:
  version: 1.0.0
  title: "文档标题"

servers:
  - url: "http://example.com:port/suffix"

paths:
  /url:
    post:
      dangerous: true
      description: "API的描述信息"
      requestBody:
        description: "API请求体的总描述"
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: string
                  example: "字段的样例值"
                  description: "字段的描述信息"
      responses:
        '200':
          description: "API返回体的总描述"
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    example: "字段的样例值"
                    description: "字段的描述信息"
                    pattern: "[\\d].\\d"