{{- if .Values.witchaind.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: witchaind-redis-deploy-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: witchaind-redis-{{ .Release.Name }}
spec:
  replicas: {{ .Values.globals.replicaCount }}
  selector:
    matchLabels:
      app: witchaind-redis-{{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/redis/redis-secret.yaml") . | sha256sum }}
      labels:
        app: witchaind-redis-{{ .Release.Name }}
    spec:
      automountServiceAccountToken: false
      containers:
        - name: redis
          image: "{{ if ne (.Values.witchaind.redis.image.registry | toString) "" }}{{ .Values.witchaind.redis.image.registry }}{{ else }}{{ .Values.globals.imageRegistry }}{{ end }}/{{ .Values.witchaind.redis.image.name }}:{{ .Values.witchaind.redis.image.tag | toString }}"
          imagePullPolicy: {{ if ne (.Values.witchaind.redis.image.imagePullPolicy | toString ) "" }}{{ .Values.witchaind.redis.image.imagePullPolicy }}{{ else }}{{ .Values.globals.imagePullPolicy }}{{ end }}
          command:
            - redis-server
            - --requirepass $(REDIS_PASSWORD)
          ports:
            - containerPort: 6379
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - redis-cli -a $REDIS_PASSWORD ping
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 90
          env:
            - name: TZ
              value: "Asia/Shanghai"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: witchaind-redis-secret-{{ .Release.Name }}
                  key: redis-password
          volumeMounts:
            - mountPath: /tmp
              name: redis-tmp
          securityContext:
            readOnlyRootFilesystem: {{ .Values.witchaind.redis.readOnly }}
          resources:
            {{- toYaml .Values.witchaind.redis.resources | nindent 12 }}
      restartPolicy: Always
      volumes:
        - name: redis-tmp
          emptyDir:
            medium: Memory
{{- end }}