{{- $authhubSecret := (lookup "v1" "Secret" .Release.Namespace "authhub-secret") }}
{{- if not $authhubSecret}}
apiVersion: v1
kind: Secret
metadata:
  name: authhub-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  mysql-password: {{ randAlphaNum 20 }}
{{- end }}