{{- if .Values.agents.ai_infra.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: ai-infra-secret-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  .env.yaml: |
{{ tpl (.Files.Get "configs/ai-infra-agent/.env.yaml") . | indent 4 }}
{{- end }}
