{{- if .Values.witchaind.minio.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: minio-service-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.witchaind.minio.service.type }}
  selector:
    app: minio-{{ .Release.Name }}
  ports:
    - port: 9000
      targetPort: 9000
      {{- if (and (eq .Values.witchaind.minio.service.type "NodePort") .Values.witchaind.minio.service.nodePort) }}
      nodePort: {{ .Values.witchaind.minio.service.nodePort }}
      {{- end }}
{{- end }}
