{{- if .Values.agents.rca.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: rca-agent-config-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
data:
  request_config.json: |-
{{ tpl (.Files.Get "configs/rca-agent/request_config.json") . | indent 4 }}
  config.json: |-
{{ tpl (.Files.Get "configs/rca-agent/config.json") . | indent 4 }}
{{- end }}