infrastructure:
  mysql:
    host: mysql-db-{{ .Values.globals.databases.app_name }}.{{ .Values.globals.databases.app_namespace }}.svc.cluster.local
    port: 3306
    username: euler_copilot
    pool_size: 100
    pool_recycle: 7200
    database: oauth2
    password: {{ .Values.globals.databases.passwords.mysql }}
  redis:
    host: redis-db-{{ .Values.globals.databases.app_name }}.{{ .Values.globals.databases.app_namespace }}.svc.cluster.local
    port: 6379
    password: {{ .Values.globals.databases.passwords.redis }}

include: "/etc/aops/conf.d"
domain: {{ .Values.globals.domain }}

services:
  log:
    log_level: "INFO"
    log_dir: "/var/log/aops"
    max_bytes: 31457280
    backup_count: 40

  email:
    server: smtp.163.com
    port: 25
    sender: xxx@163.com
    authorization_code: xxx
    smtp_ssl: false
    enabled: false
