{{- if .Values.euler_copilot.framework.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: framework-secret-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  .env: |-
{{ tpl (.Files.Get "configs/framework/.env") . | indent 4 }}
{{- end }}