{{- if .Values.euler_copilot.framework.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: framework-service-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.euler_copilot.framework.service.type }}
  selector:
    app: framework-{{ .Release.Name }}
  ports:
    - port: 8002
      targetPort: 8002
      {{- if (and (eq .Values.euler_copilot.framework.service.type "") .Values.euler_copilot.framework.service.nodePort) }}
      nodePort: {{ .Values.euler_copilot.framework.service.nodePort }}
      {{- end }}
{{- end }}