{{- if .Values.witchaind.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: witchaind-redis-db-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.witchaind.redis.service.type }}
  selector:
    app: witchaind-redis-{{ .Release.Name }}
  ports:
    - port: 6379
      targetPort: 6379
      {{- if (and (eq .Values.witchaind.redis.service.type "NodePort") .Values.witchaind.redis.service.nodePort) }}
      nodePort: {{ .Values.witchaind.redis.service.nodePort }}
      {{- end }}
{{- end }}