{{- if .Values.witchaind.redis.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: witchaind-redis-secret-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  redis-password: {{ .Values.witchaind.redis.password }}
{{- end }}