{{- if .Values.euler_copilot.web.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: web-service-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.euler_copilot.web.service.type }}
  selector:
    app: web-{{ .Release.Name }}
  ports:
    - port: 8080
      targetPort: 8080
      {{- if (and (eq .Values.euler_copilot.web.service.type "NodePort") .Values.euler_copilot.web.service.nodePort) }}
      nodePort: {{ .Values.euler_copilot.web.service.nodePort }}
      {{- end }}
{{- end }}