{{- if .Values.witchaind.backend.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: witchaind-backend-secret-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  .env: |-
{{ tpl (.Files.Get "configs/backend/.env") . | indent 4}}
  prompt.yaml: |-
{{ tpl (.Files.Get "configs/backend/prompt.yaml") . | indent 4}}
  stop_words.txt: |-
{{ tpl (.Files.Get "configs/backend/stop_words.txt") . | indent 4}}
{{- end }}