{{- if .Values.agents.rca.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: rca-agent-service-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.agents.rca.service.type }}
  selector:
    app: rca-agent-{{ .Release.Name }}
  ports:
    - port: 20030
      targetPort: 20030
      {{- if (and (eq .Values.agents.rca.service.type "") .Values.agents.rca.service.nodePort) }}
      nodePort: {{ .Values.agents.rca.service.nodePort }}
      {{- end }}
{{- end }}