{{- if .Values.databases.pgsql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: pgsql-secret-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  init.sql: |
{{ tpl (.Files.Get "configs/pgsql/init.sql") . | indent 4 }}
{{- end }}
