{{- if and .Values.databases.pgsql.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgsql-pvc-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.databases.pgsql.persistentVolumeSize }}
{{- end }}