{{- if .Values.databases.redis.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  redis-password: {{ .Values.databases.redis.password }}
{{- end }}