# 全局设置
globals:
  # [必填] 部署副本数
  replicaCount: 1
  # [必填] 镜像仓库
  imageRegistry: "hub.oepkgs.net/neocopilot"
  # [必填] 镜像拉取策略
  imagePullPolicy: IfNotPresent

databases:
  mysql:
    # [必填] 是否部署MySQL数据库实例
    enabled: true
    # 镜像设置
    image:
      # 镜像仓库。留空则使用全局设置。
      registry: ""
      # [必填] 镜像名
      name: mysql
      # [必填] 镜像标签，为8或8-arm
      tag: "8"
      # 拉取策略。留空则使用全局设置。
      imagePullPolicy: ""
    # 性能限制设置
    resources: {}
    # [必填] 容器根目录只读
    readOnly: false
    # [必填] PersistentVolume大小设置
    persistentVolumeSize: 10Gi
    # [必填] 密码设置
    password: ""
    # Service设置
    service:
      # [必填] Service类型，ClusterIP或NodePort
      type: ClusterIP
      # 当类型为nodePort时，填写主机的端口号
      nodePort:
  redis:
    # [必填] 是否部署Redis实例
    enabled: true
    # 镜像设置
    image:
      # 镜像仓库。留空则使用全局设置。
      registry: ""
      # [必填] 镜像名
      name: redis
      # [必填] 镜像标签，为7.4-alpine或7.4-alpine-arm
      tag: 7.4-alpine
      # 拉取策略。留空则使用全局设置
      imagePullPolicy: ""
    # 性能限制设置
    resources: {}
    # [必填] 容器根目录只读
    readOnly: false
    # 密码设置
    password: ""
    # Service设置
    service:
      # [必填] Service类型，ClusterIP或NodePort
      type: ClusterIP
      # 当类型为nodePort时，填写主机的端口号
      nodePort:
  pgsql:
    # [必填] 是否部署PostgreSQL实例
    enabled: true
    # 镜像设置
    image:
      # 镜像仓库。留空则使用全局设置。
      registry: ""
      # [必填] 镜像名
      name: pgsql-empty
      # [必填] 镜像标签，为pg16或pg16-arm
      tag: pg16
      # 拉取策略。留空则使用全局设置。
      imagePullPolicy: ""
    # 性能限制设置
    resources: {}
    # [必填] 容器根目录只读
    readOnly: false
    # [必填] Volume大小设置
    persistentVolumeSize: 10Gi
    # Service设置
    service:
      # [必填] Service类型，ClusterIP或NodePort
      type: ClusterIP
      # 当类型为nodePort时，填写主机的端口号
      nodePort: 
    # [必填] 密码设置
    password: ""
