{{- if .Values.authhub.backend.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: authhub-backend-service
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ default "ClusterIP" .Values.authhub.backend.service.type }}
  selector:
    app: authhub-backend
  ports:
    - port: 11120
      targetPort: 11120
      nodePort: {{ default nil .Values.authhub.backend.service.nodePort }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authhub-backend-deploy
  namespace: {{ .Release.Namespace }}
  labels:
    app: authhub-backend
spec:
  replicas: {{ default 1 .Values.globals.replicaCount }}
  selector:
    matchLabels:
      app: authhub-backend
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/backend/authhub-backend-config.yaml") . | sha256sum }}
      labels:
        app: authhub-backend
    spec:
      automountServiceAccountToken: false
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - {{ .Values.globals.arch | default "x86_64" | replace "aarch64" "arm64" | quote }}
      containers:
        - name: authhub-backend
          image: {{ .Values.authhub.backend.image | default (printf "hub.oepkgs.net/neocopilot/authhub:%s" (include "authhub.imageTag" .)) }}
          imagePullPolicy: {{ default "IfNotPresent" .Values.globals.imagePullPolicy }}
          ports:
            - containerPort: 11120
              protocol: TCP
          volumeMounts:
            - name: authhub-shared
              mountPath: /etc/aops
          livenessProbe:
            httpGet:
              path: /oauth2/applications
              port: 11120
              scheme: HTTP
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 90
          resources:
            requests:
              cpu: 0.1
              memory: 128Mi
            limits:
              {{ toYaml .Values.authhub.backend.resourceLimits | nindent 14 }}
      initContainers:
        - name: authhub-backend-copy-secret
          image: {{ .Values.authhub.secret_inject.image | default (printf "hub.oepkgs.net/neocopilot/secret_inject:%s" (include "secret_inject.imageTag" .)) }}
          imagePullPolicy: {{ default "IfNotPresent" .Values.globals.imagePullPolicy }}
          volumeMounts:
            - mountPath: /secrets/mysql-password
              name: authhub-secret-vl
              subPath: mysql-password
            - mountPath: /secrets/redis-password
              name: euler-copilot-database-vl
              subPath: redis-password
            - mountPath: /config/aops-config.yml
              name: authhub-config
              subPath: aops-config.yml
            - mountPath: /config/conf.d/authhub.yml
              name: authhub-config
              subPath: authhub.yml
            - mountPath: /config-rw
              name: authhub-shared
            - mountPath: /app/config.yaml
              name: authhub-config
              subPath: copy-config.yml
      volumes:
        - name: authhub-shared
          emptyDir:
            medium: Memory
        - name: authhub-config
          configMap:
            name: authhub-backend-config
        - name: authhub-secret-vl
          secret:
            secretName: authhub-secret
        - name: euler-copilot-database-vl
          secret:
            secretName: euler-copilot-database
{{- end -}}

{{- define "authhub.imageTag" -}}
  {{- $arch := .Values.globals.arch | default "x86_64" | replace "aarch64" "arm64" -}}
  {{- if eq $arch "arm64" -}}0.9.3-arm
  {{- else if eq $arch "x86_64" -}}0.9.3-x86
  {{- else -}}0.9.3
  {{- end -}}
{{- end -}}

{{- define "secret_inject.imageTag" -}}
  {{- $arch := .Values.globals.arch | default "x86_64" | replace "aarch64" "arm64" -}}
  {{- if eq $arch "arm64" -}}dev-arm
  {{- else if eq $arch "x86_64" -}}dev-x86
  {{- else -}}dev
  {{- end -}}
{{- end -}}
