{{- if .Values.authhub.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: authhub-backend-service-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.authhub.backend.service.type }}
  selector:
    app: authhub-backend-{{ .Release.Name }}
  ports:
    - port: 11120
      targetPort: 11120
      {{- if (and (eq .Values.authhub.backend.service.type "NodePort") .Values.authhub.backend.service.nodePort) }}
      nodePort: {{ .Values.authhub.backend.service.nodePort }}
      {{- end }}
{{- end }}