{{- if .Values.authhub.backend.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: authhub-backend-secret-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  aops-config.yml: |-
{{ tpl (.Files.Get "configs/backend/aops-config.yml") . | indent 4 }}
  authhub.yml: |-
{{ tpl (.Files.Get "configs/backend/authhub.yml") . | indent 4 }}
{{- end }}
