{{- if .Values.authelia.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "authelia.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "authelia.labels" . | nindent 4 }}
data:
  authelia.yml: |-
{{ tpl (.Files.Get "configs/authelia.yml") . | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "authelia.fullname" . }}-users
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "authelia.labels" . | nindent 4 }}
data:
  users.yml: |
    {{- .Values.users.config | nindent 4 }}
{{- end }}
