{{- if and .Values.authelia.enabled .Values.authelia.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "authelia.fullname" . }}-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "authelia.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.authelia.persistence.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.authelia.persistence.size | default (.Values.storage.authelia | default "1Gi") }}
  {{- if .Values.authelia.persistence.storageClass }}
  {{- if (eq "-" .Values.authelia.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.authelia.persistence.storageClass }}
  {{- end }}
  {{- else }}
  {{- if .Values.globals.storageClass }}
  storageClassName: {{ .Values.globals.storageClass }}
  {{- end }}
  {{- end }}
{{- end }}
